dependencies:
  another_stepper: ^1.2.2
  awesome_dialog: ^2.2.1
  barcode: ^2.2.3
  barcode_widget: ^2.0.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.0.0
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  dotted_border: ^2.0.0+3
  event: ^2.1.2
  file_picker: ^5.2.4
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.0
  flutter_verification_code: ^1.1.6
  fluttertoast: ^8.1.1
  geocoder2: ^1.1.0
  geolocator: ^8.0.0
  get: ^4.6.5
  get_storage: ^2.0.3
  google_maps_flutter: ^2.1.3
  image_picker: ^0.8.4+11
  location: ^4.2.0
  path_provider: null
  persistent_bottom_nav_bar: ^5.0.2
  photo_view: ^0.14.0
  pspdfkit_flutter: null
  textfield_search: ^0.10.0
  url_launcher: ^6.1.5
  validators: ^3.0.0

  usb_serial:
  esc_pos_utils: ^1.0.0
  screenshot:
  printing: ^5.9.3
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
#  flutter_zebra_sdk: ^0.0.4
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.18.1 <3.0.0'
flutter:
  assets:
  - assets/images/empty.png
  - assets/images/certificate.png
  - assets/images/fusion_splash.png
  - assets/svg_icons/
  - assets/images/example_product.png
  - assets/images/half_circle.png
  - assets/images/confirm_logout.png
  - assets/images/machine.png
  - assets/images/logo_in_circle.png
  - assets/images/done_invoice.png
  - assets/images/black_rect.png
  - assets/images/confirm_deliver.png
  - assets/images/yellow_rect.png
  - assets/images/splash.png
  - assets/
  - assets/images/app_icon.png
  - assets/images/default_logo.png
  fonts:
  - family: CAIRO
    fonts:
    - asset: assets/fonts/DIN_Next_LT_Arabic.ttf
  uses-material-design: true
name: fusion_warehouses
publish_to: none
version: 1.0.0+1
