import 'package:get/get.dart';
class AppStrings {
static String get phoneNumber{return "phone_number".tr;}
static String get password{return "password".tr;}
static String get login{return "Login".tr;}
static String get forgetPassword{return "forget_password".tr;}
static String get englishArabic{return "english_arabic".tr;}
static String get validPhone{return "valid_phone".tr;}
static String get enterCorrectPassword{return "enter_correct_password".tr;}
static String get notification{return "notification".tr;}
static String get noInvoices{return "no_invoices".tr;}
static String get profile{return "profile".tr;}
static String get home{return "home".tr;}
static String get completeOrders{return "complete_orders".tr;}
static String get newOrders{return "new_orders".tr;}
static String get underway{return "underway".tr;}
static String get orders{return "orders".tr;}
static String get orderDetails{return "order_details".tr;}
static String get orderWaitingStart{return "order_waiting_start".tr;}
static String get orderInWayCustomer{return "order_in_way_customer".tr;}
static String get orderDeliveredCustomer{return "order_delivered_customer".tr;}
static String get warehouse{return "warehouse".tr;}
static String get customerAddress{return "customer_address".tr;}
static String get customerName{return "customer_name".tr;}
static String get addressOnMap{return "address_on_map".tr;}
static String get amountWillCollected{return "amount_will_collected".tr;}
static String get products{return "products".tr;}
static String get quantity{return "quantity".tr;}
static String get deliveredToCustomer{return "delivered_to_customer".tr;}
static String get startDelivery{return "start_delivery".tr;}
static String get editProfile{return "edit_profile".tr;}
static String get signOut{return "sign_out".tr;}
static String get save{return "save".tr;}
static String get uploadProfilePicture{return "upload_profile_picture".tr;}
static String get confirmDeliver{return "confirm_deliver".tr;}
static String get orderNumber{return "order_number".tr;}
static String get confirmLogout{return "confirm_logout".tr;}
static String get deliveryConfirmation{return "delivery_confirmation".tr;}
static String get close{return "close".tr;}
static String get email{return "email".tr;}
static String get profileUpdated{return "profile_updated".tr;}
static String get tryAgain{return "try_again".tr;}
static String get currentOrders{return "current_orders".tr;}
static String get historyRequests{return "history_requests".tr;}
static String get freightVehicleType{return "freight_vehicle_type".tr;}
static String get type{return "type".tr;}
static String get brand{return "brand".tr;}
static String get color{return "color".tr;}
static String get plateNumber{return "plate_number".tr;}
static String get changingFreightVehicle{return "changing_freight_vehicle".tr;}
static String get shippingVehicleData{return "shipping_vehicle_data".tr;}
static String get typeOfVehicle{return "type_of_vehicle".tr;}
static String get category{return "category".tr;}
static String get addAttachment{return "add_attachment".tr;}
static String get saveVehicleData{return "save_vehicle_data".tr;}
static String get chooseTypeVehicle{return "choose_type_vehicle".tr;}
static String get addTwoAttachment{return "add_two_attachment".tr;}
static String get allFieldsRequired{return "all_fields_required".tr;}
static String get year{return "year".tr;}
static String get vehicleDataSaved{return "vehicle_data_saved".tr;}
static String get modifyVehicleInformation{return "modify_vehicle_information".tr;}
static String get backMain{return "back_main".tr;}
static String get youHaveToChooseTypeOfVehicle{return "you_have_to_choose_type_of_vehicle".tr;}
static String get manufacturingYear{return "manufacturing_year".tr;}
static String get addFrontImage{return "add_front_image".tr;}
static String get addBackgroundImage{return "add_background_image".tr;}
static String get model{return "model".tr;}
static String get addThePhoto{return "add_the_photo".tr;}
static String get noNotification{return "no_notification".tr;}
static String get newBill{return "new_bill".tr;}
static String get shopData{return "shop_data".tr;}
static String get rs{return "rs".tr;}
static String get name{return "name".tr;}
static String get taxType{return "tax_type".tr;}
static String get dateCreated{return "date_created".tr;}
static String get invoiceSummary{return "invoice_summary".tr;}
static String get total{return "total".tr;}
static String get totalAfterTax{return "total_after_tax".tr;}
static String get nodatafound{return "noDataFound".tr;}
static String get productNumber{return "product_number".tr;}
static String get amount{return "amount".tr;}
static String get tax{return "tax".tr;}
static String get taxRegistrationNumber{return "tax_registration_number".tr;}
static String get certificateTitle{return "certificate_title".tr;}
static String get expiryDate{return "expiry_date".tr;}
static String get compatibilityZakat{return "compatibility_zakat".tr;}
static String get issuingCertificate{return "issuing_certificate".tr;}
static String get plzVisitSite{return "plz_visit_site".tr;}
static String get confirm{return "confirm".tr;}
static String get currentLocation{return "current_location".tr;}
static String get createNewInvoice{return "create_new_invoice".tr;}
static String get createInvoice{return "create_invoice".tr;}
static String get addProducts{return "add_products".tr;}
static String get add{return "add".tr;}
static String get addNewProduct{return "add_new_product".tr;}
static String get productName{return "product_name".tr;}
static String get unitPrice{return "unit_price".tr;}
static String get productNumberAlreadyExists{return "product_number_already_exists".tr;}
static String get doneCreateInvoice{return "done_create_invoice".tr;}
static String get somethingWentWrong{return "something_went_wrong".tr;}
static String get numOfProducts{return "num_of_products".tr;}
static String get dailyShippingList{return "Daily_shipping_list".tr;}
static String get current{return "current".tr;}
static String get previous{return "previous".tr;}
static String get confirmation{return "confirmation".tr;}
static String get cancel{return "cancel".tr;}
static String get search{return "search".tr;}
static String get scanTheProductBarcode{return "Scan_the_product_barcode".tr;}
static String get newReceivedQuantity{return "new_received_quantity".tr;}
static String get externalPurchaseOrder{return "external_purchase_order".tr;}
static String get print{return "print".tr;}
static String get purchaseOrderNumber{return "purchase_order_number".tr;}
static String get sendToWholesalers{return "send_to_wholesalers".tr;}
static String get releaseDate{return "release_Date".tr;}
static String get purchaseOrderManagement{return "purchase_order_management".tr;}
static String get mobileNumber{return "mobile_number".tr;}
static String get releasedBy{return "released_by".tr;}
static String get internalOrderNumber{return "internal_order_number".tr;}
static String get inventory{return "inventory".tr;}
static String get applicant{return "applicant".tr;}
static String get branch{return "branch".tr;}
static String get requiredQuantity{return "required_quantity".tr;}
static String get purchasedQuantity{return "purchased_quantity".tr;}
static String get quantityReceived{return "quantity_received".tr;}
static String get returnedQuantity{return "returned_quantity".tr;}
static String get receipt{return "receipt".tr;}
static String get underTheProcedure{return "under_the_procedure".tr;}
static String get existing{return "existing".tr;}
static String get buyingSucceeded{return "buying_succeeded".tr;}
static String get complete{return "complete".tr;}
static String get storageManagement{return "storage_management".tr;}
static String get dailyShipping{return "daily_shipping".tr;}
static String get deliverWarehouses{return "deliver_warehouses".tr;}
static String get returns{return "returns".tr;}
static String get stocktaking{return "stocktaking".tr;}
static String get productData{return "product_data".tr;}
static String get purchaseManagement{return "purchase_management".tr;}
static String get foreignPurchaseOrders{return "foreign_purchase_orders".tr;}
static String get hello{return "hello".tr;}
static String get orderOwner{return "order_owner".tr;}
static String get quantityPurchasedFar{return "quantity_purchased_far".tr;}
static String get quantityReceivedFar{return "quantity_received_far".tr;}
static String get filter{return "filter".tr;}
static String get state{return "state".tr;}
static String get date{return "date".tr;}
static String get from{return "from".tr;}
static String get to{return "to".tr;}
static String get full{return "full".tr;}
static String get dialNumber{return "dial_number".tr;}
static String get scanTheExistingBarcodeOfTheProductsToConfirmTheirPresenceInTheDeliveryOrder{return "scan_the_existing_barcode_of_the_products_to_confirm_their_presence_in_the_delivery_order".tr;}
static String get barcodeScanning{return "barcode_scanning".tr;}
static String get typingTheBarcodeManually{return "typing_the_barcode_manually".tr;}
static String get orderValue{return "order_value".tr;}
static String get totalDiscount{return "total_discount".tr;}
static String get totalAfterDiscount{return "total_after_discount".tr;}
static String get discountOnProducts{return "discount_on_products".tr;}
static String get shippingValue{return "shipping_value".tr;}
static String get valueAddedTax{return "value_added_tax".tr;}
static String get enterTheBarcode{return "enter_the_barcode".tr;}
static String get barcodeConfirmation{return "barcode_confirmation".tr;}
static String get theProductIsInTheDeliveryOrder{return "the_product_is_in_the_delivery_order".tr;}
static String get barcode{return "barcode".tr;}
static String get confirmExchange{return "confirm_exchange".tr;}
static String get theProductIsNotInTheDeliveryOrder{return "the_product_is_not_in_the_delivery_order".tr;}
static String get again{return "again".tr;}
static String get deliveryOrders{return "delivery_orders".tr;}
static String get deliveryOrder{return "delivery_order".tr;}
static String get returnsConfirmation{return "returns_confirmation".tr;}
static String get theProductIsInTheReturnRequest{return "the_product_is_in_the_return_request".tr;}
static String get theProductIsNotIncludedInTheReturnRequest{return "the_product_is_not_included_in_the_return_request".tr;}
static String get confirmReceiptOfTheReturn{return "confirm_receipt_of_the_return".tr;}
static String get returnRequest{return "return_request".tr;}
static String get numberOfProduct{return "number_of_product".tr;}
static String get price{return "price".tr;}
static String get purchasePrice{return "purchase_price".tr;}
static String get editor{return "editor".tr;}
static String get reason{return "reason".tr;}
static String get editDate{return "edit_date".tr;}
static String get warehouseName{return "warehouse_name".tr;}
static String get inventoryValue{return "inventory_value".tr;}
static String get internalPurchaseOrders{return "internal_purchase_orders".tr;}
static String get pending{return "pending".tr;}
static String get processing{return "processing".tr;}
static String get purchased{return "purchased".tr;}
static String get completed{return "completed".tr;}
static String get cancelled{return "cancelled".tr;}
static String get rejected{return "rejected".tr;}
static String get enterQuantity{return "enter_quantity".tr;}
static String get waitingPayment{return "waiting_payment".tr;}
static String get waitingPaymentConfirmation{return "waiting_payment_confirmation".tr;}
static String get paymentConfirmed{return "payment_confirmed".tr;}
static String get onWay{return "on_way".tr;}
static String get delivered{return "delivered".tr;}
static String get confirmReturn{return "confirm_return".tr;}
static String get mainBranch{return "main_branch".tr;}
static String get todayStocktaking{return "today_stocktaking".tr;}
static String get stocktakingProgress{return "stocktaking_progress".tr;}
static String get all{return "all".tr;}
static String get waitingStart{return "waiting_start".tr;}
static String get inConformity{return "in_conformity".tr;}
static String get confirmingResult{return "confirming_result".tr;}
static String get inventoryEdited{return "inventory_edited".tr;}
static String get noProductFound{return "no_product_found".tr;}
static String get startInventory{return "start_inventory".tr;}
static String get submitToMatch{return "submit_to_match".tr;}
static String get adoptionInventoryResult{return "adoption_inventory_result".tr;}
static String get stockAdjustment{return "stock_adjustment".tr;}
static String get status{return "status".tr;}
static String get by{return "by".tr;}
static String get created{return "created".tr;}
static String get inventoryData{return "inventory_data".tr;}
static String get endDate{return "end_date".tr;}
static String get productsInventory{return "products_inventory".tr;}
static String get storagePlace{return "storage_place".tr;}
static String get warning1{return "warning1".tr;}
static String get warning2{return "warning2".tr;}
static String get warning3{return "warning3".tr;}
static String get warning4{return "warning4".tr;}
static String get warehouses{return "warehouses".tr;}
static String get classificationElectronicCounter{return "classification_electronic_counter".tr;}
static String get stockStatus{return "stock_status".tr;}
static String get available{return "available".tr;}
static String get outOfStock{return "out_of_stock".tr;}
static String get canNotChangeState{return "can_not_change_state".tr;}
static String get system{return "system".tr;}
static String get theInventory{return "the_inventory".tr;}
static String get actual{return "actual".tr;}
static String get pendingToUnderProcessing{return "pending_to_under_processing".tr;}
static String get processingToPurchased{return "processing_to_purchased".tr;}
static String get purchasedToCompleted{return "purchased_to_completed".tr;}
static String get cash{return "cash".tr;}
static String get deferred{return "deferred".tr;}
static String get collectionMethod{return "collection_method".tr;}
static String get invoiceNumber{return "invoice_number".tr;}
static String get totalInvoice{return "total_invoice".tr;}
static String get invoiceDate{return "invoice_date".tr;}
static String get deferredDate{return "deferred_date".tr;}
static String get supplier{return "supplier".tr;}
static String get attachments{return "attachments".tr;}
static String get chooseFile{return "choose_file".tr;}
static String get required{return "required".tr;}
static String get checkout{return "checkout".tr;}
static String get actualPurchasePrice{return "actual_purchase_price".tr;}
static String get dateOfShipment{return "date_of_shipment".tr;}
static String get newPurchasedQuantity{return "new_purchased_quantity".tr;}
static String get quantityPurchasedSoFar{return "quantity_purchased_so_far".tr;}
static String get refund{return "refund".tr;}
static String get returnQuantity{return "return_quantity".tr;}
static String get location{return "location".tr;}
static String get seeStorePage{return "see_store_page".tr;}
static String get address{return "address".tr;}

static String get allCategories{return "all_categories".tr;}
static String get allBrands{return "all_brands".tr;}
static String get youDontHaveAccessToLoginApp{return "you_dont_have_access_to_login_app".tr;}
static String get youDontHaveAccess{return "you_dont_have_access".tr;}
static String get invalidPhoneOrPassword{return "invalid_phone_or_password".tr;}
static String get description{return "description".tr;}
static String get stock{return "stock".tr;}
static String get all_categories2{return "all_categories2".tr;}



}